* Վերացականի և կոնկրետի դիալեկտիկան գիտա-տեսական ճանաչողության մեջ
  Հեղինակ: Է. Իլյենկով
** Ա - Վերացականը օբյեկտիվ ճշմարտության հասնելու միջոց:
*** Օրիգինալ Տեքստ                                                      :rus:
    Հայտնի է, որ ճչմարտությունը վերացական չի լինում այն միչտ կոնկրետ է:
    Մյուս կողմից, ընդունված է, որ վերացականը համընդհանուր ձև է, որում և
    որի միջոցով մտածողություն կարող է հասնել օբյեկտիվ ճշմարտությանը:
** Բ - Վերացականը և կոնկրետի դիալեկտիկական միասնությունը
*** Հայերեն տեքստ                                                        :am:
    Վերացականը և կոնկրետը հանդիսանում են անբաժանելի ներքին հակադրություններ, 
    որոնց կենդանի դիալեկտիկական միասնության մեջ միայն կարող է իրականացվել
    տեսական ճանաչողության գործընթացը, տրամաբանական գործընթացը: ՞ ՞ ՞ ՞
** Գ - Գիտա-տեսական ճանաչողության մեջ Վ և Կ դիալեկտիկակայի      :rivin:title:
   հիմքերի լուսաբանումը Կ. Մարքսի տեքստը
*** Օրիգինալ Տեքստ                                                      :rus:
    Основы для решения и освещения вопроса о диалектике абстрактного и конкретного 
    в научно-теоретическом познании заложил Карл Маркс в своем знаменитом фрагменте, 
    известном под названием «Введения» к «К критике политической экономии». Мысли,
    развитые там, естественно, и должны послужить для нас исходным пунктом при 
    анализе данной проблемы.
*** Հայերեն տեքստ                                                        :am:
    Գիտա-տեսական ճանաչողության մեջ Վ և Կ դիալեկտիկակայի հարցի լուծման և 
    լուսաբանման հիմքերին է նվիրված Կ. Մարքսի՝ «Քաղաքական տնտեսության քննադատություն»
    աշխատության «Ներածություն»-ը, որը  խնդրի վերլուծության համար, 
    բնականաբանր, կհանդիսանա ելակետային:

** Դ - Կոնկրետությունը ըստ Մարքսի և ավանդական ընկալման                  :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    Маркс определяет конкретное, конкретность как «единство многообразного». 
    С точки зрения старой, традиционной логики это может показаться парадоксальным: 
    ведь сведение чувственно данного многообразия к единству, в нем обнаруживающемуся,
    кажется, на первый взгляд, задачей выработки абстракции, задачей выработки 
    общего, «родового» понятия.
*** Հայերեն տեքստ                                                       :am:
    Մարքսը սահմանում է կոնկրետությունը որպես «բազմազանության միասնություն»:
    Հին ավանդական մտածողության տեսակետից դա կարող է թվալ պարադոքսալ, քանի որ զգայականով
    ընկալված բազմազանության բերումը միասնության, նրա մեջ գտնվողի համար, առաջին հայացքից 
    թվում է, որ դա աբստրակցիա մշակելու խնդիր է, այսինքն ստեղծել ընդհանուր, ելակետային 
    հասկացություն:

** Ե - Մարքսի արտահայտությունը բառագործածության տրամաբանության տեսակետից   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    Если понимать задачу мышления как сведение чувственно данного многообразия к некоторому 
    отвлеченному единству, к «абстрактно общему», то выражение Маркса и в самом деле может 
    показаться просто необычным, не принятым в логике словоупотреблением.
*** Հայերեն տեքստ                                                       :am:
    Եթե մտածողության խնդիրը հասկանանք որպես, զգայականով ընկալված բազմազանության հանգումը 
    ինչ-որ վերացական միասնության, այլ կերպ ասած «վերացական ընդհանուրի», ապա Մարքսի 
    արտահայտություն իրականում կարող է թվալ ուղղակի անսովոր և չընդունված բառագործածության
    տրամաբանության տեսակետից:

** Զ - Կոնկրետությունը որպես ճանաչողության առարկայի ոբյեկտիվ բնութագիրչ  
*** Օրիգինալ Տեքստ                                                      :rus:
    Однако в этом кратком, афористическом определении конкретности подытожена вся суть
    марксовой, диалектико-материалистической логики во всем ее принципиальном отличии 
    от логики старой. Если развернуть краткое определение Маркса, то оно может быть 
    выражено так: конкретность есть прежде всего объективная характеристика предмета 
    познания, совпадающая по своему смыслу с понятием внутренней взаимообусловленности, 
    взаимосвязи всех сторон, черточек, граней, качеств, форм или условий существования 
    объекта, притом взаимосвязи, специфичной именно для данного и ни для какого 
    другого объекта.
*** Հայերեն տեքստ                                                       :am:
    Սակայն այս կարճ, կոնկրետության աֆորիստական սահմանման մեջ, հանրագումարված է մարքսյան՝ 
    դիալեկտիկա-մատերիալիստական տրամաբանության էությունը, իր ամբողջ սկզբունքային տարբերություններով 
    հանդերձ հին տրամաբանությունից: Եթե բացենք Մարքսի կարճ սահմանումը, ապա այն կներկայանա 
    հետևյալ կերպ. կոնկրետությունը նախ և առաջ ճանաչողության առարկայի օբյեկտիվ բնութագիրն է.
    որը իր իմաստով համընկնում է ներքին փոխպայմանավորվածություն հասկացության հետ. այսինքն բոլոր կողմերի, 
    գծերի, նիստերի, որակների, ձևերի  փոխադարձ կապը կամ համենկնում է օբյեկտի գոյության պայմանին:
    Բացի դրանից, փոխադարձ կապերը, պետք է լինեն յուրահատուկ հենց այդ տվսծ օբյեկտի և ոչ մի ուրիշ այլ օբյեկտի համար:

** Է - Կոնկրետ գիտելիք և օբյեկտիվ ճշմարտություն                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    В соответствии с высказываниями Маркса только такое знание может и должно быть 
    квалифицированно как конкретное (а тем самым и как объективно истинное), которое отражает,
    духовно воспроизводит эту внутреннюю взаимосвязь исследуемого объекта.
*** Հայերեն տեքստ                                                       :am:
    Ըստ Մարքսի տված սահմանումի միայն այդպիսի գիտելիքը կարող է և պետք է որակել որպես կոնկրետ գիտելիք
    (և դրանով հանդերձ և որպես օբյեկտիվ ճշմարտություն), որը անդրադարձնում ու հոգևոր վերարտադրում է,
    հետազոտվող օբյեկտի այդ ներքին փոխադարձ կապը:

** Ը -                    :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    Поэтому единственной субъективной формой, в которой может быть отражена, схвачена, воспроизведена
    объективная конкретность, является «единство многообразных определений», то есть система логически
    связанных между собой категорий, каждая из которых по своему объективному содержанию есть отражение
    одной из сторон, характеризующих специфику исследуемого объекта.
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    Это весьма важный для логики пункт марксовых взглядов: конкретная истина возможна только в 
    форме системы категорий.
*** Հայերեն տեքստ                                                       :am:

** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
    С другой стороны, абстракция, абстрактное как таковое, с этой точки зрения, есть не более как 
    односторонность, синоним односторонности знания. Поэтому вопрос о соотношении абстрактного и конкретного
    в мышлении, в научно-теоретическом познании выступает прежде всего как различие между односторонним и 
    всесторонним знанием о предмете.
*** Հայերեն տեքստ                                                       :am:

** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
** Դ -                   :rivin-title:
*** Օրիգինալ Տեքստ                                                      :rus:
*** Հայերեն տեքստ                                                       :am:
